// <auto-generated />
using System;
using CA1_BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CA1_BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424111855_MealIngredientsRelationship1")]
    partial class MealIngredientsRelationship1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CA1_BackEnd.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CalorieDensity")
                        .HasColumnType("float");

                    b.Property<double>("CaloriesPerServing")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("DietaryFiberPercentage")
                        .HasColumnType("float");

                    b.Property<double>("EnergyContent")
                        .HasColumnType("float");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<double>("Fiber")
                        .HasColumnType("float");

                    b.Property<bool>("IsOrganic")
                        .HasColumnType("bit");

                    b.Property<string>("IsVegetarian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MacronutrientComposition")
                        .HasColumnType("float");

                    b.Property<int?>("MealId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutrientGroups")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("ServingSize")
                        .HasColumnType("float");

                    b.Property<double>("SodiumContent")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 3.6000000000000001,
                            Fiber = 0.0,
                            IsOrganic = true,
                            IsVegetarian = "false",
                            MacronutrientComposition = 0.0,
                            Name = "Chicken",
                            NutrientGroups = "Protein",
                            Origin = "Ireland",
                            Price = 8.99m,
                            Protein = 31.0,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 0.29999999999999999,
                            Fiber = 0.0,
                            IsOrganic = false,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Rice",
                            NutrientGroups = "Carbohydrates",
                            Origin = "Italy",
                            Price = 2.50m,
                            Protein = 2.7000000000000002,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 0.20000000000000001,
                            Fiber = 0.0,
                            IsOrganic = true,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Tomato",
                            NutrientGroups = "Vitamins",
                            Origin = "Spain",
                            Price = 1.20m,
                            Protein = 0.90000000000000002,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 33.0,
                            Fiber = 0.0,
                            IsOrganic = false,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Cheese",
                            NutrientGroups = "Protein,Fats",
                            Origin = "France",
                            Price = 5.75m,
                            Protein = 25.0,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 5,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 1.5,
                            Fiber = 0.0,
                            IsOrganic = true,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Pasta",
                            NutrientGroups = "Carbohydrates",
                            Origin = "Italy",
                            Price = 1.99m,
                            Protein = 13.0,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 6,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 0.20000000000000001,
                            Fiber = 0.0,
                            IsOrganic = true,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Tomato",
                            NutrientGroups = "Vitamins",
                            Origin = "Italy",
                            Price = 2.49m,
                            Protein = 0.90000000000000002,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 7,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 0.5,
                            Fiber = 0.0,
                            IsOrganic = false,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Garlic",
                            NutrientGroups = "Vitamins",
                            Origin = "Italy",
                            Price = 1.79m,
                            Protein = 6.4000000000000004,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 8,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 29.0,
                            Fiber = 0.0,
                            IsOrganic = true,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Parmesan",
                            NutrientGroups = "Protein,Fats",
                            Origin = "Italy",
                            Price = 3.99m,
                            Protein = 35.799999999999997,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 9,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 0.59999999999999998,
                            Fiber = 0.0,
                            IsOrganic = true,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Basil",
                            NutrientGroups = "Vitamins",
                            Origin = "Italy",
                            Price = 1.49m,
                            Protein = 3.2000000000000002,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        },
                        new
                        {
                            Id = 10,
                            CalorieDensity = 0.0,
                            CaloriesPerServing = 0.0,
                            Carbohydrates = 0.0,
                            DietaryFiberPercentage = 0.0,
                            EnergyContent = 0.0,
                            Fats = 100.0,
                            Fiber = 0.0,
                            IsOrganic = false,
                            IsVegetarian = "true",
                            MacronutrientComposition = 0.0,
                            Name = "Olive Oil",
                            NutrientGroups = "Fats",
                            Origin = "Italy",
                            Price = 4.99m,
                            Protein = 0.0,
                            ServingSize = 0.0,
                            SodiumContent = 0.0
                        });
                });

            modelBuilder.Entity("CA1_BackEnd.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.Property<double>("TotalCarbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("TotalCholesterol")
                        .HasColumnType("float");

                    b.Property<double>("TotalFat")
                        .HasColumnType("float");

                    b.Property<double>("TotalFiber")
                        .HasColumnType("float");

                    b.Property<double>("TotalProtein")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Calories = 210.0,
                            Category = "Breakfast",
                            CookTime = 10,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Pancakes",
                            Picture = "pancakes.jpg",
                            PrepTime = 15,
                            Protein = 6.0,
                            Rating = 4.5,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 8.5,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Calories = 180.0,
                            Category = "Breakfast",
                            CookTime = 8,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Omelette",
                            Picture = "omelette.jpg",
                            PrepTime = 10,
                            Protein = 22.0,
                            Rating = 4.2000000000000002,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 12.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Calories = 220.0,
                            Category = "Breakfast",
                            CookTime = 10,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "French Toast",
                            Picture = "french-toast.jpg",
                            PrepTime = 10,
                            Protein = 7.0,
                            Rating = 4.4000000000000004,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 9.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Calories = 320.0,
                            Category = "Breakfast",
                            CookTime = 10,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Breakfast Burrito",
                            Picture = "breakfast-burrito.jpg",
                            PrepTime = 20,
                            Protein = 14.0,
                            Rating = 4.2999999999999998,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 14.5,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 13,
                            Calories = 180.0,
                            Category = "Breakfast",
                            CookTime = 0,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Smoothie Bowl",
                            Picture = "smoothie-bowl.jpg",
                            PrepTime = 10,
                            Protein = 37.0,
                            Rating = 4.7999999999999998,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 5.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 14,
                            Calories = 190.0,
                            Category = "Breakfast",
                            CookTime = 5,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Avocado Toast",
                            Picture = "avocado-toast.jpg",
                            PrepTime = 5,
                            Protein = 4.0,
                            Rating = 4.5999999999999996,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 11.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 15,
                            Calories = 160.0,
                            Category = "Breakfast",
                            CookTime = 0,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Granola Yogurt",
                            Picture = "granola-yogurt.jpg",
                            PrepTime = 5,
                            Protein = 40.0,
                            Rating = 4.7000000000000002,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 6.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 16,
                            Calories = 150.0,
                            Category = "Breakfast",
                            CookTime = 5,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Scrambled Eggs",
                            Picture = "scrambled-eggs.jpg",
                            PrepTime = 5,
                            Protein = 11.0,
                            Rating = 4.2999999999999998,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 10.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 17,
                            Calories = 230.0,
                            Category = "Breakfast",
                            CookTime = 20,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Breakfast Muffins",
                            Picture = "breakfast-muffins.jpg",
                            PrepTime = 20,
                            Protein = 6.0,
                            Rating = 4.2000000000000002,
                            Servings = 4,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 7.5,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 18,
                            Calories = 200.0,
                            Category = "Breakfast",
                            CookTime = 0,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Chia Pudding",
                            Picture = "chia-pudding.jpg",
                            PrepTime = 10,
                            Protein = 6.0,
                            Rating = 4.5,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 9.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 19,
                            Calories = 350.0,
                            Category = "Lunch",
                            CookTime = 10,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Chicken Salad",
                            Picture = "chicken-salad.jpg",
                            PrepTime = 15,
                            Protein = 25.0,
                            Rating = 4.2999999999999998,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 15.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 20,
                            Calories = 300.0,
                            Category = "Lunch",
                            CookTime = 10,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Grilled Cheese Sandwich",
                            Picture = "grilled-cheese.jpg",
                            PrepTime = 5,
                            Protein = 10.0,
                            Rating = 4.5999999999999996,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 18.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 21,
                            Calories = 270.0,
                            Category = "Lunch",
                            CookTime = 5,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Turkey Wrap",
                            Picture = "turkey-wrap.jpg",
                            PrepTime = 10,
                            Protein = 18.0,
                            Rating = 4.2000000000000002,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 9.5,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 22,
                            Calories = 240.0,
                            Category = "Lunch",
                            CookTime = 0,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Caesar Salad",
                            Picture = "caesar-salad.jpg",
                            PrepTime = 15,
                            Protein = 7.0,
                            Rating = 4.0999999999999996,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 14.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 23,
                            Calories = 320.0,
                            Category = "Lunch",
                            CookTime = 10,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "BLT Sandwich",
                            Picture = "blt.jpg",
                            PrepTime = 10,
                            Protein = 12.0,
                            Rating = 4.4000000000000004,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 16.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 24,
                            Calories = 210.0,
                            Category = "Lunch",
                            CookTime = 0,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Veggie Wrap",
                            Picture = "veggie-wrap.jpg",
                            PrepTime = 10,
                            Protein = 6.0,
                            Rating = 4.5,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 7.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 25,
                            Calories = 150.0,
                            Category = "Lunch",
                            CookTime = 20,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Tomato Soup",
                            Picture = "tomato-soup.jpg",
                            PrepTime = 10,
                            Protein = 4.0,
                            Rating = 4.2999999999999998,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 5.5,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 26,
                            Calories = 290.0,
                            Category = "Lunch",
                            CookTime = 10,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Chicken Wrap",
                            Picture = "chicken-wrap.jpg",
                            PrepTime = 10,
                            Protein = 20.0,
                            Rating = 4.4000000000000004,
                            Servings = 1,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 11.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 27,
                            Calories = 330.0,
                            Category = "Lunch",
                            CookTime = 10,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Pasta Salad",
                            Picture = "pasta-salad.jpg",
                            PrepTime = 15,
                            Protein = 9.0,
                            Rating = 4.2000000000000002,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 12.5,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 28,
                            Calories = 260.0,
                            Category = "Lunch",
                            CookTime = 15,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Quinoa Bowl",
                            Picture = "quinoa-bowl.jpg",
                            PrepTime = 15,
                            Protein = 10.0,
                            Rating = 4.7000000000000002,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 8.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 29,
                            Calories = 480.0,
                            Category = "Dinner",
                            CookTime = 25,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Spaghetti Bolognese",
                            Picture = "spaghetti.jpg",
                            PrepTime = 20,
                            Protein = 22.0,
                            Rating = 4.5999999999999996,
                            Servings = 4,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 20.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 30,
                            Calories = 420.0,
                            Category = "Dinner",
                            CookTime = 15,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Grilled Salmon",
                            Picture = "salmon.jpg",
                            PrepTime = 15,
                            Protein = 34.0,
                            Rating = 4.7999999999999998,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 18.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 31,
                            Calories = 390.0,
                            Category = "Dinner",
                            CookTime = 15,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Beef Stir Fry",
                            Picture = "beef-stir-fry.jpg",
                            PrepTime = 20,
                            Protein = 28.0,
                            Rating = 4.5,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 16.5,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 32,
                            Calories = 310.0,
                            Category = "Dinner",
                            CookTime = 20,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Vegetable Curry",
                            Picture = "veg-curry.jpg",
                            PrepTime = 20,
                            Protein = 9.0,
                            Rating = 4.4000000000000004,
                            Servings = 4,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 13.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 33,
                            Calories = 550.0,
                            Category = "Dinner",
                            CookTime = 20,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Chicken Alfredo",
                            Picture = "alfredo.jpg",
                            PrepTime = 20,
                            Protein = 30.0,
                            Rating = 4.5999999999999996,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 22.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 34,
                            Calories = 360.0,
                            Category = "Dinner",
                            CookTime = 10,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Shrimp Tacos",
                            Picture = "shrimp-tacos.jpg",
                            PrepTime = 15,
                            Protein = 20.0,
                            Rating = 4.7000000000000002,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 14.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 35,
                            Calories = 280.0,
                            Category = "Dinner",
                            CookTime = 30,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Stuffed Peppers",
                            Picture = "stuffed-peppers.jpg",
                            PrepTime = 25,
                            Protein = 12.0,
                            Rating = 4.2999999999999998,
                            Servings = 4,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 10.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 36,
                            Calories = 600.0,
                            Category = "Dinner",
                            CookTime = 20,
                            Difficulty = "Hard",
                            IsVegetarian = false,
                            Name = "Lamb Chops",
                            Picture = "lamb-chops.jpg",
                            PrepTime = 20,
                            Protein = 35.0,
                            Rating = 4.5,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 25.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 37,
                            Calories = 250.0,
                            Category = "Dinner",
                            CookTime = 20,
                            Difficulty = "Easy",
                            IsVegetarian = false,
                            Name = "Baked Cod",
                            Picture = "baked-cod.jpg",
                            PrepTime = 10,
                            Protein = 28.0,
                            Rating = 4.4000000000000004,
                            Servings = 2,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 9.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        },
                        new
                        {
                            Id = 38,
                            Calories = 410.0,
                            Category = "Dinner",
                            CookTime = 30,
                            Difficulty = "Medium",
                            IsVegetarian = false,
                            Name = "Mushroom Risotto",
                            Picture = "risotto.jpg",
                            PrepTime = 15,
                            Protein = 10.0,
                            Rating = 4.5999999999999996,
                            Servings = 3,
                            TotalCarbohydrates = 0.0,
                            TotalCholesterol = 0.0,
                            TotalFat = 17.0,
                            TotalFiber = 0.0,
                            TotalProtein = 0.0
                        });
                });

            modelBuilder.Entity("CA1_BackEnd.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A balanced weekly meal plan",
                            Name = "Healthy Week"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Meals focused on high protein intake",
                            Name = "High Protein"
                        });
                });

            modelBuilder.Entity("CA1_BackEnd.Models.Ingredient", b =>
                {
                    b.HasOne("CA1_BackEnd.Models.Meal", "Meal")
                        .WithMany("Ingredients")
                        .HasForeignKey("MealId");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("CA1_BackEnd.Models.Meal", b =>
                {
                    b.HasOne("CA1_BackEnd.Models.Plan", null)
                        .WithMany("Meals")
                        .HasForeignKey("PlanId");
                });

            modelBuilder.Entity("CA1_BackEnd.Models.Meal", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("CA1_BackEnd.Models.Plan", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
