name: Build and deploy ASP.Net Core app to Azure Web App - marksapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: marksapi
  AZURE_WEBAPP_PACKAGE_PATH: ./publish
  AZURE_APIM_RESOURCE_PATH: /marksapi
  AZURE_APIM_RESOURCEGROUP: CollegeY4_PersonalAccount
  AZURE_APIM_SERVICENAME: CA1BackEndapi
  AZURE_APIM_API_ID: CA1BackEnd
  AZURE_APIM_APPSERVICEURL: https://marksapi-d7fvaucyewh4excm.canadaeast-01.azurewebsites.net
  SWASHBUCKLE_ASPNET_CORE_CLI_PACKAGE_VERSION: 6.9.0
  API_IMPORT_SPECIFICATION_PATH: ./publish/swagger.json
  API_IMPORT_DLL: ./CA1_BackEnd/bin/Release/net8.0/CA1_BackEnd.dll
  API_IMPORT_VERSION: v1
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  SOLUTION_PATH: CA1_BackEnd/CA1_BackEnd.sln
  PROJECT_PATH: CA1_BackEnd/CA1_BackEnd.csproj

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: List repo files
        run: Get-ChildItem -Path . -Recurse -Include *.sln,*.csproj | Select-Object FullName

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore packages
        run: dotnet restore "${{ env.SOLUTION_PATH }}"

      - name: Build
        run: dotnet build "${{ env.SOLUTION_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test "${{ env.SOLUTION_PATH }}" --no-build --configuration ${{ env.CONFIGURATION }}
        continue-on-error: true

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

      - name: Install Swashbuckle CLI
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version ${{ env.SWASHBUCKLE_ASPNET_CORE_CLI_PACKAGE_VERSION }}

      - name: Generate OpenAPI Specification
        run: swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" "${{ env.API_IMPORT_VERSION }}"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Import API into Azure API Management
        run: |
          az apim api import `
            --path "${{ env.AZURE_APIM_RESOURCE_PATH }}" `
            --resource-group "${{ env.AZURE_APIM_RESOURCEGROUP }}" `
            --service-name "${{ env.AZURE_APIM_SERVICENAME }}" `
            --api-id "${{ env.AZURE_APIM_API_ID }}" `
            --service-url "${{ env.AZURE_APIM_APPSERVICEURL }}" `
            --specification-path "${{ env.API_IMPORT_SPECIFICATION_PATH }}" `
            --specification-format OpenApi `
            --subscription-required false

      - name: Logout from Azure
        run: az logout
        if: always()
